workflows:
  android-native-workflow:
    name: Android Native CMMS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - android_credentials
      vars:
        PACKAGE_NAME: "com.example"
      android_ndk: true
      java: 17
    triggering:
      events:
        - push
      branches:
        - main
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build Android APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - ibr2hashim@gmail.com
        notify:
          success: true
          failure: true
